services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DEBUG=1
      - PYTHONPATH=/app:/app/ecom
    command: gunicorn --bind 0.0.0.0:8000 ecom.wsgi:application